### ISSUE TITLE
can't replace when using maven-war-plugin

### ISSUE THREAD

**Issue by henryyan** [juven/portable-config-maven-plugin#12]
``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-war-plugin</artifactId>
    <version>2.2</version>
    <configuration>
        <warName>${project.artifactId}</warName>
    </configuration>
</plugin>
```

---

file **foo-web-2.0.0-SNAPSHOT.war** not exsit, but **foo-web.war**

---

[INFO] --- portable-config-maven-plugin:1.1.5:replace-package (default) @ foo-web ---
[INFO] Replacing: /Users/henryyan/foo-web/target/foo-web-2.0.0-SNAPSHOT
[INFO] Replacing file: /Users/henryyan/foo-web/target/foo-web-2.0.0-SNAPSHOT/WEB-INF/classes/log4j.properties
[INFO] Replacing: /Users/henryyan/foo-web/target/foo-web-2.0.0-SNAPSHOT.war
[WARNING] File: /Users/henryyan/foo-web/target/foo-web-2.0.0-SNAPSHOT.war/WEB-INF/classes/log4j.properties does not exist or is a directory.

**Comment by juven** [comment]
please configure build.finalName instead of warName in maven-war-plugin
