### ISSUE TITLE
xml has namespace,how i handle this?

### ISSUE THREAD

**Issue by itchanges** [juven/portable-config-maven-plugin#9]
xml demo: 
<dubbo:registry id="test" protocol="zookeeper"
        address="x.x.x.x:port,x.x.x.x:port"/>

&lt;replace xpath="/beans/dubbo:registry[@id='dev']/@address"&gt; has no effect

**Comment by itchanges** [comment]
建议发布一个新版本了，spring配置文件多个namespace是比较常见的。 commit 9b69bf5b00fa5261d53a925233dc49b6f7b67309
Author: Juven Xu juvenshun@gmail.com
Date:   Thu Aug 22 01:00:30 2013 +0800

```
also support user specifed namespace in his own xpath

this namespace is usually not the root namespace
```

感谢一下，刚好用到这个插件了。给现存的项目写个打包脚本很方便，现在的项目直接用两份文件保存两份配置。用这个插件可以不改原来东西，直接加点东西就OK了。

**Comment by juven** [comment]
最新SNAPSHOT已经解决你问题了对吧？我抽时间梳理下，然后发版本。

感谢使用

**Comment by itchanges** [comment]
公司的搭建的maven库不大好使，有时间提交到maven中央库最好了，这样其他同事也方便用
再赞一个，好东西

**Comment by itchanges** [comment]
where your 1.1.5 snapshots  upload? I can search it in https://oss.sonatype.org/index.htm. but I don't know where the repository, I want configure the repository in my settings.xml, Thanks

**Comment by juven** [comment]
@itchanges please use this repository url for latest snapshots: https://oss.sonatype.org/content/groups/public/
and I will make a new release ASAP
